// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzleYSvZvaNrNAGT6pQoEfj77fV0vC__k',
    appId: '1:887565525205:web:5b31d34c0cdab51d5ac25c',
    messagingSenderId: '887565525205',
    projectId: 'my-code-star-project',
    authDomain: 'my-code-star-project.firebaseapp.com',
    storageBucket: 'my-code-star-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPG6sdsonYbJSdt5a8DaIcNKaNs6thCo',
    appId: '1:887565525205:android:197da0b3bcb379345ac25c',
    messagingSenderId: '887565525205',
    projectId: 'my-code-star-project',
    storageBucket: 'my-code-star-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGXz2vhMkBbfgYr7u31qvV5HTI0m3PJBA',
    appId: '1:887565525205:ios:4e0c5e11d03b72805ac25c',
    messagingSenderId: '887565525205',
    projectId: 'my-code-star-project',
    storageBucket: 'my-code-star-project.appspot.com',
    iosBundleId: 'com.example.codeVidhya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGXz2vhMkBbfgYr7u31qvV5HTI0m3PJBA',
    appId: '1:887565525205:ios:d08e153e870aba9c5ac25c',
    messagingSenderId: '887565525205',
    projectId: 'my-code-star-project',
    storageBucket: 'my-code-star-project.appspot.com',
    iosBundleId: 'com.example.codeVidhya.RunnerTests',
  );
}
